### ISSUE TITLE
Move the drawChart functions out of their parent (no nested functions)

### ISSUE THREAD

**Issue by marsmith** [marsmith/nowcast#8]
pass them the data it needs to to create the chart as arguments.  This is good practice, and down the line makes the function reusable for something else.

**Comment by marsmith** [comment]
You can the functions the data array and the options as arguments
```
var dataArray = [
	['', ''],
	['Correct Exceed', CorrectExceed],
	['Correct Non-Exceed', CorrectNonExceed],
	['False Exceed', FalseExceed],
	['False Non-Exceed', FalseNonExceed],
	['', 0]
]
```
as an argument

**Comment by marsmith** [comment]
Now that I look at this, if you do what I suggest, you wont need two seperate drawChart functions.....

**Comment by marsmith** [comment]
ugh, i hate this but it looks like how you have it is correct based on this example:
https://developers.google.com/chart/interactive/docs/basic_multiple_charts

**Comment by marsmith** [comment]
I would just suggest naming them explicitly based on what they are drawing, instead of 'drawchart' and drawchart2'.   Then can still be moved out of the parent function

**Comment by rmcwilliams** [comment]
Resolved
